% Jakub Nowak 2017 01 05

function [state,fS] = getHoloFromBank (z0,x0,y0,D,zR,Nx,dx,Ny,dy,path)

name=sprintf('d%02d_zh%02d_x%02d_y%02d',round(D*1e6),round(abs(z0)*1e3),round(abs(x0)*1e4),round(abs(y0)*1e4));
nameT=sprintf('d%02d_zh%02d_x%02d_y%02d',round(D*1e6),round(abs(z0)*1e3),round(abs(y0)*1e4),round(abs(x0)*1e4));

fileList=dir([path,filesep,'*',name,'*.mat']);
fileListT=dir([path,filesep,'*',nameT,'*.mat']);
files=fullfile(path,{fileList.name fileListT.name}');

state=0;
if numel(files)>0
    i=1;
    cases=[x0 y0; x0 -y0; -x0 y0; -x0 -y0;...
        -y0 -x0; -y0 x0; y0 -x0; y0 x0];
    
    while state<1 && i<=numel(files)
        file=load(files{i}); 
        if file.xR==0 && file.yR==0 && file.zR==zR && ...
                file.dx==dx && file.dy==dy && all(eq(size(file.fieldS),[Ny Nx]),2)
            state=find(all(eq(cases,repmat([file.x0 file.y0],8,1)),2));
        else
            state=0;
        end
        i=i+1;
    end
end

if state>0
    
    if state/4>1
        fS=transpose(file.fieldS);
    else
        fS=file.fieldS;
    end
    
    if rem(state,4)==2
        fS=flip(fS,1);
    elseif rem(state,4)==3
        fS=flip(fS,2);
    elseif rem(state,4)==0
        fS=flip(flip(fS,1),2);
    end
    
    fprintf('Hologram generated by case %d from file %s.\n',state,files{i-1})
    
else
    disp('Proper hologram not found in databank.')
    fS=0;
end   

end